CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  display_name VARCHAR(128) NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','member') NOT NULL DEFAULT 'member',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS activities (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(128) UNIQUE,
  title_ja VARCHAR(255) NULL,
  title_zh VARCHAR(255) NULL,
  title_en VARCHAR(255) NULL,
  summary_ja TEXT NULL,
  summary_zh TEXT NULL,
  summary_en TEXT NULL,
  body_md_ja MEDIUMTEXT NULL,
  body_md_zh MEDIUMTEXT NULL,
  body_md_en MEDIUMTEXT NULL,
  cover_image VARCHAR(255) NULL,
  status ENUM('draft','published') NOT NULL DEFAULT 'draft',
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS schedule_events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  event_date DATE NOT NULL,
  event_time TIME NULL,
  title VARCHAR(255) NOT NULL,
  detail TEXT NULL,
  category ENUM('meeting','event','other') NOT NULL DEFAULT 'other',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bugs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bug_id VARCHAR(32) NOT NULL UNIQUE,
  project VARCHAR(128) NOT NULL,
  severity ENUM('P0','P1','P2','P3') NOT NULL DEFAULT 'P3',
  title VARCHAR(255) NOT NULL,
  steps TEXT NOT NULL,
  expected TEXT NULL,
  actual TEXT NULL,
  reporter VARCHAR(128) NOT NULL,
  status ENUM('Pending','Confirmed','Fixing','Fixed','Deferred','Duplicate') NOT NULL DEFAULT 'Pending',
  handler VARCHAR(128) NULL,
  solution TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS system_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(64) NOT NULL DEFAULT 'SYSTEM',
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
